### ISSUE TITLE
Crash in webview

### ISSUE THREAD

**Issue by tigerbalm** [JcMinarro/Philology#34]
**Describe the bug**
App crash is occured.

**To Reproduce**
Steps to reproduce the problem:
1. Launch app using Chrome webview.
2. Choose Input window and Open EditText with keyboard.
3. Using Google voice via keyboard's option menu, input any text.
4. Select text that is input by Google voice.
5. And Copy or select text.
6. Repeat steps 4 to 5 1 to 2 times.
7. App crash is occured.

**Expected behavior**
No crash

**Library version**
2.0.1

**Logs/Screenshots**

Chrome version: 84.0.4147.89  Channel: stable
OS Version: 10.0
Flash Version: 

Crash log is following.
Please help to not crash.

07-28 15:46:45.919 11202 11202 W System.err: android.view.InflateException: Binary XML file line #16 in com.google.android.webview:layout/text_edit_suggestion_list_footer: Binary XML file line #16 in com.google.android.webview:layout/text_edit_suggestion_list_footer: Error inflating class TextView
07-28 15:46:45.920 11202 11202 W System.err: Caused by: android.view.InflateException: Binary XML file line #16 in com.google.android.webview:layout/text_edit_suggestion_list_footer: Error inflating class TextView
07-28 15:46:45.920 11202 11202 W System.err: Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x7f100037
07-28 15:46:45.920 11202 11202 W System.err: 	at android.content.res.Resources.getText(Resources.java:367)
07-28 15:46:45.920 11202 11202 W System.err: 	at android.widget.TextView.setText(TextView.java:6622)
07-28 15:46:45.920 11202 11202 W System.err: 	at com.jcminarro.philology.transformer.TextViewTransformer$reword$2$1.invoke(TextViewTransformer.kt:20)
07-28 15:46:45.921 11202 11202 W System.err: 	at com.jcminarro.philology.transformer.TextViewTransformer$reword$2$1.invoke(TextViewTransformer.kt:8)
07-28 15:46:45.921 11202 11202 W System.err: 	at com.jcminarro.philology.ViewTransformer$DefaultImpls.setTextIfExists(ViewTransformer.kt:10)
07-28 15:46:45.921 11202 11202 W System.err: 	at com.jcminarro.philology.transformer.TextViewTransformer.setTextIfExists(TextViewTransformer.kt:8)
07-28 15:46:45.921 11202 11202 W System.err: 	at com.jcminarro.philology.transformer.TextViewTransformer$reword$2.invoke(TextViewTransformer.kt:20)
07-28 15:46:45.921 11202 11202 W System.err: 	at com.jcminarro.philology.transformer.TextViewTransformer$reword$2.invoke(TextViewTransformer.kt:8)
07-28 15:46:45.921 11202 11202 W System.err: 	at com.jcminarro.philology.transformer.AttributeSetExtensionsKt.forEach(AttributeSetExtensions.kt:8)
07-28 15:46:45.921 11202 11202 W System.err: 	at com.jcminarro.philology.transformer.TextViewTransformer.reword(TextViewTransformer.kt:18)
07-28 15:46:45.921 11202 11202 W System.err: 	at com.jcminarro.philology.transformer.TextViewTransformer.reword(TextViewTransformer.kt:13)
07-28 15:46:45.921 11202 11202 W System.err: 	at com.jcminarro.philology.PhilologyInterceptorKt.reword(PhilologyInterceptor.kt:22)
07-28 15:46:45.921 11202 11202 W System.err: 	at com.jcminarro.philology.PhilologyInterceptorKt.access$reword(PhilologyInterceptor.kt:1)
07-28 15:46:45.921 11202 11202 W System.err: 	at com.jcminarro.philology.PhilologyInterceptor.rewordView(PhilologyInterceptor.kt:17)
07-28 15:46:45.921 11202 11202 W System.err: 	at com.jcminarro.philology.PhilologyInterceptor.intercept(PhilologyInterceptor.kt:12)
07-28 15:46:45.921 11202 11202 W System.err: 	at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.kt:30)
07-28 15:46:45.921 11202 11202 W System.err: 	at io.github.inflationx.viewpump.ViewPump.inflate(ViewPump.kt:36)
07-28 15:46:45.922 11202 11202 W System.err: 	at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$WrapperFactory2.onCreateView(-ViewPumpLayoutInflater.kt:358)
07-28 15:46:45.922 11202 11202 W System.err: 	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1061)
07-28 15:46:45.922 11202 11202 W System.err: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
07-28 15:46:45.922 11202 11202 W System.err: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
07-28 15:46:45.922 11202 11202 W System.err: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
07-28 15:46:45.922 11202 11202 W System.err: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
07-28 15:46:45.922 11202 11202 W System.err: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
07-28 15:46:45.922 11202 11202 W System.err: 	at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:57)
07-28 15:46:45.922 11202 11202 W System.err: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
07-28 15:46:45.922 11202 11202 W System.err: 	at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:48)
07-28 15:46:45.922 11202 11202 W System.err: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
07-28 15:46:45.922 11202 11202 W System.err: 	at vL.<init>(chromium-TrichromeWebViewGoogle.aab-stable-1:24)
07-28 15:46:45.922 11202 11202 W System.err: 	at zL.<init>(chromium-TrichromeWebViewGoogle.aab-stable-1:1)
07-28 15:46:45.922 11202 11202 W System.err: 	at org.chromium.content.browser.input.TextSuggestionHost.showTextSuggestionMenu(chromium-TrichromeWebViewGoogle.aab-stable-1:5)
07-28 15:46:45.922 11202 11202 W System.err: 	at android.os.MessageQueue.nativePollOnce(Native Method)
07-28 15:46:45.922 11202 11202 W System.err: 	at android.os.MessageQueue.next(MessageQueue.java:336)
07-28 15:46:45.923 11202 11202 W System.err: 	at android.os.Looper.loop(Looper.java:174)
07-28 15:46:45.923 11202 11202 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7576)
07-28 15:46:45.923 11202 11202 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
07-28 15:46:45.923 11202 11202 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
07-28 15:46:45.923 11202 11202 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:937)
07-28 15:46:45.929 11202 11202 F chromium: [FATAL:jni_android.cc(249)] Please include Java exception stack in crash report

**Comment by syzhugh** [comment]
@tigerbalm  Hi ～I have the same problem but not this application . I wonder know how to "Launch app using Chrome webview" . I want to reproduce this problem .
