### ISSUE TITLE
java.lang.RuntimeException: Unable to instantiate receiver cn.***.MyReceiver: java.lang.ClassCastException: io.github.inflationx.viewpump.ViewPumpContextWrapper cannot be cast to android.app.ContextImpl

### ISSUE THREAD

**Issue by MugWorld** [JcMinarro/Philology#7]
at android.app.ActivityThread.handleReceiver(ActivityThread.java:3351)
        at android.app.ActivityThread.-wrap17(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1812)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6771)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)
     Caused by: java.lang.ClassCastException: io.github.inflationx.viewpump.ViewPumpContextWrapper cannot be cast to android.app.ContextImpl
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3338)
        at android.app.ActivityThread.-wrap17(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1812) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:192) 
        at android.app.ActivityThread.main(ActivityThread.java:6771) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)

**Comment by MugWorld** [comment]
How to resolve this crash?

**Comment by JcMinarro** [comment]
This crash is not from our library.
BTW, the problem is that you are trying to cast an instance of `io.github.inflationx.viewpump.ViewPumpContextWrapper` to `android.app.ContextImpl` and it is not possible
